<template>
    <Layout>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
        <p>money</p>
    </Layout>
</template>

<script>
    export default {
        name: "Money"
    }
</script>

<style lang="scss" scoped>
</style>